import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/header";
import { Footer } from "@/components/footer";

import { headers } from "next/headers";
import AppkitProvider from "@/context/appkit";
import { WalletProvider } from "@/context/wallet";
import { PollingProvider } from "@/context/polling-context";
import { POLLING_INTERVALS } from "@/constants/api";
import { Toaster } from "@/components/ui/sonner";
import { QueryProvider } from "@/providers/QueryClientProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const headersObj = await headers();
  const cookies = headersObj.get("cookie");

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col`}
      >
        <QueryProvider>
          <AppkitProvider cookies={cookies}>
            <WalletProvider>
              <PollingProvider
                ordersInterval={POLLING_INTERVALS.ORDERS}
                balanceInterval={POLLING_INTERVALS.BALANCE}
                heightInterval={POLLING_INTERVALS.HEIGHT}
              >
                <Header />
                <main className="w-full max-w-screen-3xl mx-auto px-4 sm:px-6 lg:px-8 py-8 flex-1">
                  {children}
                </main>
                <Footer />
                <Toaster />
              </PollingProvider>
            </WalletProvider>
          </AppkitProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
